"""
CreatePageTool — Agent tool to dynamically create and register new personalised pages.

The agent provides backend Python code (a FastAPI route function) and frontend
HTML. The tool:
1. Validates the code (no dangerous imports).
2. Syntax-checks the backend Python via compile().
3. Writes the frontend asset to disk.
4. Registers the backend route dynamically.
5. Records the page in the personalised_pages memory table.
6. Returns a success status so the agent can confirm to the user.
"""
import logging
import re
import sqlite3
import time
from pathlib import Path
from typing import Any

from .base import BaseTool

logger = logging.getLogger(__name__)

# Imports that are never allowed in agent-generated backend code.
# Network, subprocess, file-system mutation, and reflection escapes are all
# rejected by a substring match on `import` / `from ... import ...` lines.
_BLOCKED_IMPORTS = frozenset([
    # Network / external API
    "anthropic", "openai", "requests", "httpx", "aiohttp", "urllib",
    "socket", "smtplib", "ftplib", "telnetlib",
    # Subprocess / shell
    "subprocess", "os.system", "os.popen", "pty", "pexpect",
    # Filesystem destruction
    "shutil.rmtree", "shutil.move", "tempfile.mktemp",
    # Reflection / dynamic code loading
    "importlib", "ctypes", "cffi", "marshal", "dill", "pickle",
])

# Tokens that, if present in agent-generated code, indicate an attempt to
# escape the sandbox (call into builtins, evaluate strings, etc.). These are
# matched as whole identifiers and reject the page outright.
_BLOCKED_TOKENS = frozenset([
    "eval", "exec", "compile", "__import__", "__builtins__",
    "__class__", "__bases__", "__subclasses__", "__mro__",
    "__globals__", "__getattribute__",
    "globals", "locals", "vars",
    "open",   # the helpers expose query_health/write_memory; raw open() not needed
])
_TOKEN_RE = re.compile(r"\b(" + "|".join(re.escape(t) for t in _BLOCKED_TOKENS) + r")\b")

# Deduplication: track recent page creations {page_id: timestamp}
_recent_creations: dict[str, float] = {}
_DEDUP_WINDOW_SECS = 60.0

_SCHEMA_DESCRIPTION = """
Create a new personalised page that will appear as a screen in the iOS app.
Provide:
- page_id: unique slug, e.g. "sleep_trend_v1"
- display_name: human-readable title shown on the screen
- description: what this page does
- backend_code: Python code defining `route_handler(request)` that returns a dict.
  The framework auto-injects `HEALTH_DB_PATH` and `MEMORY_DB_PATH` as global str variables.
  Available imports: sqlite3, json, datetime, pathlib.
  NO AI/LLM calls, NO external HTTP requests.
- frontend_html: complete single-page HTML that fetches data from
  /api/personalised-pages/{page_id}/data and renders it. Use vanilla JS only.
"""


class CreatePageTool(BaseTool):
    """Dynamically create and register a new personalised page."""

    name = "create_page"

    def __init__(self, memory_db_path: Path, user_id: str, data_store_path: Path = None):
        self.memory_db_path = Path(memory_db_path)
        self.user_id = user_id
        self.data_store_path = data_store_path
        _project_root = Path(__file__).resolve().parent.parent.parent.parent
        self._pages_dir = _project_root / "data" / "personalised_pages"
        self._pages_dir.mkdir(parents=True, exist_ok=True)

    # Relative path from project root to page_helpers.py (portable across moves)
    _HELPERS_REL = "backend/agent/tools/page_helpers.py"

    def get_definition(self) -> dict[str, Any]:
        return self._get_definition_from_json("create_page")

    def _build_route_source(self, page_id: str, db_path: Path, backend_code: str) -> str:
        """Build the full route.py source with preamble. Uses __file__-relative path for helpers."""
        _project_root = Path(__file__).resolve().parent.parent.parent.parent
        helpers_abs = _project_root / self._HELPERS_REL
        return (
            f"# Auto-generated by CreatePageTool for page_id={page_id!r}\n"
            f"import sqlite3, json, statistics\nfrom datetime import datetime, timedelta\nfrom pathlib import Path\n"
            f"HEALTH_DB_PATH = {str(db_path / (self.user_id + '_data.db'))!r}\n"
            f"MEMORY_DB_PATH = {str(self.memory_db_path / (self.user_id + '.db'))!r}\n\n"
            f"# --- Page Helpers (query_health, query_memory, write_memory, ensure_table, etc.) ---\n"
            f"# Resolve helpers relative to this file's project root for portability\n"
            f"_helpers_path = Path(__file__).resolve().parent.parent.parent.parent / {self._HELPERS_REL!r}\n"
            f"if not _helpers_path.exists():\n"
            f"    _helpers_path = Path({str(helpers_abs)!r})  # fallback to absolute\n"
            f"exec(open(str(_helpers_path)).read())\n\n"
            + backend_code
        )

    async def execute(self, page_id: str, display_name: str, backend_code: str,
                      frontend_html: str, description: str = "",
                      patch: bool = False) -> dict[str, Any]:
        # 0. Deduplication — prevent the LLM from creating the same page multiple times in one turn
        # (skip dedup window when patch=True — patching is an intentional update)
        now = time.time()
        if not patch:
            last_created = _recent_creations.get(page_id)
            if last_created is not None and (now - last_created) < _DEDUP_WINDOW_SECS:
                logger.info("create_page: skipping duplicate creation of '%s' (created %.0fs ago)", page_id, now - last_created)
                return {
                    "success": True,
                    "page_id": page_id,
                    "display_name": display_name,
                    "frontend_url": f"/api/personalised-pages/{page_id}/",
                    "data_url": f"/api/personalised-pages/{page_id}/data",
                    "message": f"Page '{display_name}' already exists (created moments ago). No duplicate created.",
                }

        # 0b. Patch mode: update existing page preserving unmodified parts
        if patch:
            page_dir = self._pages_dir / page_id
            if page_dir.exists():
                return await self._patch_page(
                    page_id, display_name, description, backend_code, frontend_html
                )
            # Page doesn't exist yet — fall through to normal creation

        # 1. Validate page_id format
        if not re.match(r'^[a-z0-9_]{1,64}$', page_id):
            return {"success": False, "error": "page_id must be lowercase alphanumeric/underscore, max 64 chars"}

        # 2. Security: block dangerous imports in backend code
        for blocked in _BLOCKED_IMPORTS:
            pattern = re.compile(r'\b(import|from)\b.*\b' + re.escape(blocked.replace('.', r'\.')))
            if pattern.search(backend_code):
                return {
                    "success": False,
                    "error": f"Backend code contains blocked import: '{blocked}'. Agent-created pages may not call external APIs or AI services."
                }

        # 2a. Block sandbox-escape tokens (eval/exec/__import__/__builtins__/...)
        token_match = _TOKEN_RE.search(backend_code)
        if token_match:
            return {
                "success": False,
                "error": (
                    f"Backend code contains a blocked identifier: "
                    f"'{token_match.group(1)}'. Use the provided helpers "
                    f"(query_health, query_memory, write_memory, ensure_table) "
                    f"instead of dynamic code evaluation or reflection."
                ),
            }

        # 2b. Syntax-check the backend Python code before writing to disk
        #     Build the full source that will actually be saved (with preamble).
        db_path = self.data_store_path or Path("data/data_stores")
        route_source = self._build_route_source(page_id, db_path, backend_code)
        try:
            compile(route_source, f"<personalised_page:{page_id}/route.py>", "exec")
        except SyntaxError as se:
            logger.warning("create_page: syntax error in backend_code for '%s': %s (line %s)", page_id, se.msg, se.lineno)
            return {
                "success": False,
                "error": (
                    f"The backend Python code has a syntax error: {se.msg} at line {se.lineno}. "
                    "Please fix the code and try again."
                ),
            }

        # 3. Write frontend asset
        page_dir = self._pages_dir / page_id
        page_dir.mkdir(parents=True, exist_ok=True)
        html_path = page_dir / "index.html"
        html_path.write_text(frontend_html, encoding="utf-8")

        # 4. Write backend route module (route_source was already built & validated above)
        route_path = page_dir / "route.py"
        route_path.write_text(route_source, encoding="utf-8")

        # 5. Register in personalised_pages table
        db_file = self.memory_db_path / f"{self.user_id}.db"
        try:
            with sqlite3.connect(str(db_file), timeout=10) as conn:
                conn.execute(
                    """INSERT INTO personalised_pages
                       (page_id, display_name, description, backend_route, frontend_asset, status)
                       VALUES (?, ?, ?, ?, ?, 'active')
                       ON CONFLICT(page_id) DO UPDATE SET
                           display_name = excluded.display_name,
                           description = excluded.description,
                           backend_route = excluded.backend_route,
                           frontend_asset = excluded.frontend_asset,
                           status = 'active'""",
                    (
                        page_id,
                        display_name,
                        description,
                        f"/api/personalised-pages/{page_id}/data",
                        str(html_path),
                    ),
                )
                conn.commit()
        except Exception as e:
            logger.error("create_page: DB error: %s", e)
            return {"success": False, "error": f"DB registration failed: {e}"}

        # 6. Record creation time for deduplication
        _recent_creations[page_id] = time.time()

        logger.info("create_page: registered '%s' (%s)", page_id, display_name)
        return {
            "success": True,
            "page_id": page_id,
            "display_name": display_name,
            "frontend_url": f"/api/personalised-pages/{page_id}/",
            "data_url": f"/api/personalised-pages/{page_id}/data",
            "message": f"Page '{display_name}' created. It will appear as a new page in the iOS app."
        }

    async def _patch_page(
        self,
        page_id: str,
        display_name: str,
        description: str,
        backend_code: str,
        frontend_html: str,
    ) -> dict[str, Any]:
        """Update an existing page preserving parts that are not provided."""
        page_dir = self._pages_dir / page_id
        html_path = page_dir / "index.html"
        route_path = page_dir / "route.py"

        # Read existing files so we can preserve unchanged parts
        existing_html = html_path.read_text(encoding="utf-8") if html_path.exists() else ""
        existing_route = route_path.read_text(encoding="utf-8") if route_path.exists() else ""

        new_html = frontend_html if frontend_html else existing_html
        new_backend = backend_code if backend_code else ""

        # If neither existing nor new content is available, report an error
        if not new_html and not existing_html:
            return {"success": False, "error": f"Cannot patch page '{page_id}': no existing frontend HTML and none provided."}
        if not new_backend and not existing_route:
            return {"success": False, "error": f"Cannot patch page '{page_id}': no existing backend route and none provided."}

        if new_backend:
            # Rebuild full route source and syntax-check it
            db_path = self.data_store_path or Path("data/data_stores")
            route_source = self._build_route_source(page_id, db_path, new_backend)
            try:
                compile(route_source, f"<personalised_page:{page_id}/route.py>", "exec")
            except SyntaxError as se:
                logger.warning("create_page patch: syntax error in backend_code for '%s': %s (line %s)", page_id, se.msg, se.lineno)
                return {
                    "success": False,
                    "error": f"Patched backend code has a syntax error: {se.msg} at line {se.lineno}. Fix and retry.",
                }
            route_path.write_text(route_source, encoding="utf-8")
        else:
            route_source = existing_route  # keep unchanged

        html_path.write_text(new_html, encoding="utf-8")

        # DB UPDATE — only overwrite non-empty fields
        db_file = self.memory_db_path / f"{self.user_id}.db"
        try:
            with sqlite3.connect(str(db_file), timeout=10) as conn:
                updates: list = []
                params: list = []
                if display_name:
                    updates.append("display_name = ?")
                    params.append(display_name)
                if description:
                    updates.append("description = ?")
                    params.append(description)
                if updates:
                    params.append(page_id)
                    conn.execute(
                        f"UPDATE personalised_pages SET {', '.join(updates)} WHERE page_id = ?",
                        params,
                    )
                    conn.commit()
        except Exception as e:
            logger.error("create_page patch: DB error: %s", e)
            return {"success": False, "error": f"DB update failed: {e}"}

        _recent_creations[page_id] = time.time()
        effective_name = display_name or page_id
        logger.info("create_page: patched '%s' (%s)", page_id, effective_name)
        return {
            "success": True,
            "page_id": page_id,
            "display_name": effective_name,
            "frontend_url": f"/api/personalised-pages/{page_id}/",
            "data_url": f"/api/personalised-pages/{page_id}/data",
            "message": f"Page '{effective_name}' patched successfully.",
        }
