"""
Apple Health feature specification: raw form, processing, aggregation, unit, display.

Single source of truth for all 48 features.
"""
# Aggregation: SUM for additive, MEAN for rate/instant
AGG_SUM = "sum"
AGG_MEAN = "mean"

# Feature spec: raw_form, processing, aggregation, unit, display_unit, format
FEATURE_SPEC = {
    # === Activity / Movement (SUM) ===
    "steps": {
        "raw_form": "Incremental step count per sync (1–2456)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "count",
        "display_unit": "steps",
        "format": "{:.0f}",
    },
    "distance": {
        "raw_form": "Distance per record (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
    },
    "distance_cycling": {
        "raw_form": "Cycling distance per record (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
    },
    "flights_climbed": {
        "raw_form": "Floors per record (1–14)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "count",
        "display_unit": "floors",
        "format": "{:.0f}",
    },
    "exercise_time": {
        "raw_form": "Exercise duration per record (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
    },
    "stand_time": {
        "raw_form": "Stand duration per record (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
    },
    "physical_effort": {
        "raw_form": "Metabolic equivalent (kcal/hr·kg)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal/hr·kg",
        "display_unit": "kcal/hr·kg",
        "format": "{:.1f}",
    },
    "six_minute_walk": {
        "raw_form": "Distance in 6-min walk test (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "m",
        "format": "{:.0f}",
    },
    # === Energy (SUM) ===
    "active_energy": {
        "raw_form": "Active calories per record (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
    },
    "resting_energy": {
        "raw_form": "Basal calories per record (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
    },
    # === Duration (SUM) ===
    "time_in_daylight": {
        "raw_form": "Duration in daylight per record (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
    },
    "sleep": {
        "raw_form": "Category (InBed/Asleep/etc) with startDate, endDate",
        "processing": "value = (endDate - startDate).total_seconds()",
        "aggregation": "merge_intervals",  # Special: merge overlapping sleep intervals
        "unit": "s",
        "display_unit": "min",
        "format": "{:.0f}",
        "display_scale": 1 / 60,  # s -> min for chart
        "note": "Legacy feature. Use sleep_asleep for total sleep time.",
    },
    # === Detailed Sleep Features (from sleep_analyzer) ===
    "sleep_in_bed": {
        "raw_form": "Total time in bed (merged InBed intervals)",
        "processing": "Merge overlapping InBed intervals",
        "aggregation": "merge_intervals",
        "unit": "s",
        "display_unit": "min",
        "format": "{:.0f}",
        "display_scale": 1 / 60,
        "note": "Total time spent in bed, including sleep and awake periods.",
    },
    "sleep_asleep": {
        "raw_form": "Total sleep time (merged Asleep intervals)",
        "processing": "Merge overlapping Asleep* intervals",
        "aggregation": "merge_intervals",
        "unit": "s",
        "display_unit": "min",
        "format": "{:.0f}",
        "display_scale": 1 / 60,
        "note": "Actual sleep time, excluding awake periods.",
    },
    "sleep_awake": {
        "raw_form": "Awake time while in bed",
        "processing": "Sum Awake periods",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.0f}",
        "display_scale": 1 / 60,
        "note": "Time spent awake while in bed.",
    },
    "sleep_core": {
        "raw_form": "Core sleep duration (merged intervals)",
        "processing": "Merge Core sleep intervals",
        "aggregation": "merge_intervals",
        "unit": "s",
        "display_unit": "min",
        "format": "{:.0f}",
        "display_scale": 1 / 60,
        "note": "Core/light sleep stage duration.",
    },
    "sleep_deep": {
        "raw_form": "Deep sleep duration (merged intervals)",
        "processing": "Merge Deep sleep intervals",
        "aggregation": "merge_intervals",
        "unit": "s",
        "display_unit": "min",
        "format": "{:.0f}",
        "display_scale": 1 / 60,
        "note": "Deep sleep stage duration.",
    },
    "sleep_rem": {
        "raw_form": "REM sleep duration (merged intervals)",
        "processing": "Merge REM sleep intervals",
        "aggregation": "merge_intervals",
        "unit": "s",
        "display_unit": "min",
        "format": "{:.0f}",
        "display_scale": 1 / 60,
        "note": "REM (Rapid Eye Movement) sleep stage duration.",
    },
    "sleep_efficiency": {
        "raw_form": "Sleep efficiency percentage",
        "processing": "(asleep / in_bed) × 100",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "note": "Percentage of time asleep while in bed. Higher is better.",
    },
    "sleep_core_pct": {
        "raw_form": "Core sleep percentage",
        "processing": "(core / asleep) × 100",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "note": "Percentage of sleep time in core/light stage.",
    },
    "sleep_deep_pct": {
        "raw_form": "Deep sleep percentage",
        "processing": "(deep / asleep) × 100",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "note": "Percentage of sleep time in deep stage.",
    },
    "sleep_rem_pct": {
        "raw_form": "REM sleep percentage",
        "processing": "(rem / asleep) × 100",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "note": "Percentage of sleep time in REM stage.",
    },
    "sleep_stage_coverage": {
        "raw_form": "Sleep stage coverage percentage",
        "processing": "((core + deep + rem) / asleep) × 100",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "note": "Percentage of sleep with identified stages. Lower means more unclassified sleep.",
    },
    # === Intake (SUM) ===
    "water": {
        "raw_form": "Volume per record (mL)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "mL",
        "display_unit": "mL",
        "format": "{:.0f}",
    },
    "dietary_potassium": {
        "raw_form": "Potassium per record (mg)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "mg",
        "display_unit": "mg",
        "format": "{:.0f}",
    },
    # === Audio exposure (SUM) ===
    "environmental_audio": {
        "raw_form": "Sound level exposure (dBASPL)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "dBASPL",
        "display_unit": "dB",
        "format": "{:.1f}",
    },
    "headphone_audio": {
        "raw_form": "Headphone sound exposure (dBASPL)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "dBASPL",
        "display_unit": "dB",
        "format": "{:.1f}",
    },
    # === Heart / Cardio (MEAN) ===
    "heart_rate": {
        "raw_form": "Instantaneous BPM (count/min)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "count/min",
        "display_unit": "bpm",
        "format": "{:.0f}",
    },
    "resting_heart_rate": {
        "raw_form": "Resting BPM",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "count/min",
        "display_unit": "bpm",
        "format": "{:.0f}",
    },
    "walking_heart_rate_avg": {
        "raw_form": "Average BPM during walk",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "count/min",
        "display_unit": "bpm",
        "format": "{:.0f}",
    },
    "heart_rate_variability": {
        "raw_form": "SDNN (ms)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "ms",
        "display_unit": "ms",
        "format": "{:.0f}",
    },
    "heart_rate_recovery": {
        "raw_form": "BPM drop in 1 min after exercise",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "count/min",
        "display_unit": "bpm",
        "format": "{:.0f}",
    },
    "blood_oxygen": {
        "raw_form": "SpO2 as fraction (0.73–1.0)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.0f}",
        "display_scale": 100,  # 0.98 -> 98%
    },
    "vo2max": {
        "raw_form": "mL/kg·min",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "mL/(kg·min)",
        "display_unit": "mL/(kg·min)",
        "format": "{:.1f}",
    },
    # === Respiratory (MEAN) ===
    "respiratory_rate": {
        "raw_form": "Breaths per minute",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "count/min",
        "display_unit": "/min",
        "format": "{:.0f}",
    },
    # === Walking / Gait (MEAN) ===
    "walking_speed": {
        "raw_form": "Speed (m/s or km/hr)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "m/s",
        "display_unit": "m/s",
        "format": "{:.2f}",
    },
    "walking_step_length": {
        "raw_form": "Length per step (m)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "m",
        "display_unit": "cm",
        "format": "{:.1f}",
        "display_scale": 100,
    },
    "walking_asymmetry": {
        "raw_form": "Percentage (0–1)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "display_scale": 100,
    },
    "walking_double_support": {
        "raw_form": "Percentage (0–1)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "display_scale": 100,
    },
    "walking_steadiness": {
        "raw_form": "Score 0–1",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "%",
        "display_unit": "%",
        "format": "{:.1f}",
        "display_scale": 100,
    },
    # === Stairs / Running (MEAN) ===
    "stair_descent_speed": {
        "raw_form": "Speed (m/s)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "m/s",
        "display_unit": "m/s",
        "format": "{:.2f}",
    },
    "stair_ascent_speed": {
        "raw_form": "Speed (m/s)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "m/s",
        "display_unit": "m/s",
        "format": "{:.2f}",
    },
    "running_speed": {
        "raw_form": "Speed (m/s)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "m/s",
        "display_unit": "km/h",
        "format": "{:.1f}",
        "display_scale": 3.6,
    },
    "running_power": {
        "raw_form": "Power (W)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "W",
        "display_unit": "W",
        "format": "{:.0f}",
    },
    "running_ground_contact": {
        "raw_form": "Time (ms)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "ms",
        "display_unit": "ms",
        "format": "{:.0f}",
    },
    "running_stride_length": {
        "raw_form": "Length (m)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "m",
        "display_unit": "cm",
        "format": "{:.1f}",
        "display_scale": 100,
    },
    "running_vertical_oscillation": {
        "raw_form": "Vertical motion (cm)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "cm",
        "display_unit": "cm",
        "format": "{:.1f}",
    },
    # === Sleep quality (MEAN) ===
    "sleeping_wrist_temp": {
        "raw_form": "Deviation from baseline (°C)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "degC",
        "display_unit": "°C",
        "format": "{:.2f}",
    },
    "sleeping_breathing_disturbances": {
        "raw_form": "Events per hour (count)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "count",
        "display_unit": "/hr",
        "format": "{:.1f}",
    },
    # === Body (MEAN) ===
    "body_mass": {
        "raw_form": "Weight (kg)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "kg",
        "display_unit": "kg",
        "format": "{:.1f}",
    },
    "body_mass_index": {
        "raw_form": "BMI (count)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "count",
        "display_unit": "kg/m²",
        "format": "{:.1f}",
    },
    "height": {
        "raw_form": "Height (cm)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "cm",
        "display_unit": "cm",
        "format": "{:.0f}",
    },
    # === Category / Event (MEAN, value=0) ===
    "stand_hour": {
        "raw_form": "Category (Idle/Stand/etc)",
        "processing": "value=0",
        "aggregation": AGG_MEAN,
        "unit": "count",
        "display_unit": "events",
        "format": "{:.0f}",
    },
    "handwashing": {
        "raw_form": "Category event",
        "processing": "value=0",
        "aggregation": AGG_MEAN,
        "unit": "count",
        "display_unit": "events",
        "format": "{:.0f}",
    },
    "mindful_session": {
        "raw_form": "Session duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
    },
    "audio_exposure_event": {
        "raw_form": "Category event",
        "processing": "value=0",
        "aggregation": AGG_MEAN,
        "unit": "count",
        "display_unit": "events",
        "format": "{:.0f}",
    },
    "high_heart_rate_event": {
        "raw_form": "Category event",
        "processing": "value=0",
        "aggregation": AGG_MEAN,
        "unit": "count",
        "display_unit": "events",
        "format": "{:.0f}",
    },
    "low_cardio_fitness_event": {
        "raw_form": "Category event",
        "processing": "value=0",
        "aggregation": AGG_MEAN,
        "unit": "count",
        "display_unit": "events",
        "format": "{:.0f}",
    },
    "sleep_duration_goal": {
        "raw_form": "Target hours (hr)",
        "processing": "Store as-is",
        "aggregation": AGG_MEAN,
        "unit": "hr",
        "display_unit": "h",
        "format": "{:.1f}",
    },
    # === Workouts ===
    # -- Running --
    "workout_running_duration": {
        "raw_form": "Running workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f3c3",
        "description": "Running workout duration",
    },
    "workout_running_distance": {
        "raw_form": "Running workout distance (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
        "category": "Workouts",
        "emoji": "\U0001f3c3",
        "description": "Running workout distance",
    },
    "workout_running_energy": {
        "raw_form": "Running workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f3c3",
        "description": "Running workout energy burned",
    },
    # -- Cycling --
    "workout_cycling_duration": {
        "raw_form": "Cycling workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f6b4",
        "description": "Cycling workout duration",
    },
    "workout_cycling_distance": {
        "raw_form": "Cycling workout distance (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
        "category": "Workouts",
        "emoji": "\U0001f6b4",
        "description": "Cycling workout distance",
    },
    "workout_cycling_energy": {
        "raw_form": "Cycling workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f6b4",
        "description": "Cycling workout energy burned",
    },
    # -- Swimming --
    "workout_swimming_duration": {
        "raw_form": "Swimming workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f3ca",
        "description": "Swimming workout duration",
    },
    "workout_swimming_distance": {
        "raw_form": "Swimming workout distance (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
        "category": "Workouts",
        "emoji": "\U0001f3ca",
        "description": "Swimming workout distance",
    },
    "workout_swimming_energy": {
        "raw_form": "Swimming workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f3ca",
        "description": "Swimming workout energy burned",
    },
    # -- Walking --
    "workout_walking_duration": {
        "raw_form": "Walking workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f6b6",
        "description": "Walking workout duration",
    },
    "workout_walking_distance": {
        "raw_form": "Walking workout distance (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
        "category": "Workouts",
        "emoji": "\U0001f6b6",
        "description": "Walking workout distance",
    },
    "workout_walking_energy": {
        "raw_form": "Walking workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f6b6",
        "description": "Walking workout energy burned",
    },
    # -- Hiking --
    "workout_hiking_duration": {
        "raw_form": "Hiking workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f97e",
        "description": "Hiking workout duration",
    },
    "workout_hiking_distance": {
        "raw_form": "Hiking workout distance (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
        "category": "Workouts",
        "emoji": "\U0001f97e",
        "description": "Hiking workout distance",
    },
    "workout_hiking_energy": {
        "raw_form": "Hiking workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f97e",
        "description": "Hiking workout energy burned",
    },
    # -- Yoga --
    "workout_yoga_duration": {
        "raw_form": "Yoga workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f9d8",
        "description": "Yoga workout duration",
    },
    "workout_yoga_energy": {
        "raw_form": "Yoga workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f9d8",
        "description": "Yoga workout energy burned",
    },
    # -- Strength Training --
    "workout_strength_duration": {
        "raw_form": "Strength training workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f4aa",
        "description": "Strength training workout duration",
    },
    "workout_strength_energy": {
        "raw_form": "Strength training workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f4aa",
        "description": "Strength training workout energy burned",
    },
    # -- HIIT --
    "workout_hiit_duration": {
        "raw_form": "HIIT workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\u26a1",
        "description": "HIIT workout duration",
    },
    "workout_hiit_energy": {
        "raw_form": "HIIT workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\u26a1",
        "description": "HIIT workout energy burned",
    },
    # -- Elliptical --
    "workout_elliptical_duration": {
        "raw_form": "Elliptical workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f3bd",
        "description": "Elliptical workout duration",
    },
    "workout_elliptical_distance": {
        "raw_form": "Elliptical workout distance (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
        "category": "Workouts",
        "emoji": "\U0001f3bd",
        "description": "Elliptical workout distance",
    },
    "workout_elliptical_energy": {
        "raw_form": "Elliptical workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f3bd",
        "description": "Elliptical workout energy burned",
    },
    # -- Rowing --
    "workout_rowing_duration": {
        "raw_form": "Rowing workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f6a3",
        "description": "Rowing workout duration",
    },
    "workout_rowing_distance": {
        "raw_form": "Rowing workout distance (m)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "m",
        "display_unit": "km",
        "format": "{:.2f}",
        "display_scale": 0.001,
        "category": "Workouts",
        "emoji": "\U0001f6a3",
        "description": "Rowing workout distance",
    },
    "workout_rowing_energy": {
        "raw_form": "Rowing workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f6a3",
        "description": "Rowing workout energy burned",
    },
    # -- Core Training --
    "workout_core_duration": {
        "raw_form": "Core training workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f9d1\u200d\U0001f4bb",
        "description": "Core training workout duration",
    },
    "workout_core_energy": {
        "raw_form": "Core training workout energy burned (kcal)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "kcal",
        "display_unit": "kcal",
        "format": "{:.0f}",
        "category": "Workouts",
        "emoji": "\U0001f9d1\u200d\U0001f4bb",
        "description": "Core training workout energy burned",
    },
    # -- Flexibility --
    "workout_flexibility_duration": {
        "raw_form": "Flexibility workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\U0001f938",
        "description": "Flexibility workout duration",
    },
    # -- Cooldown --
    "workout_cooldown_duration": {
        "raw_form": "Cooldown workout duration (s)",
        "processing": "Store as-is",
        "aggregation": AGG_SUM,
        "unit": "s",
        "display_unit": "min",
        "format": "{:.1f}",
        "display_scale": 1 / 60,
        "category": "Workouts",
        "emoji": "\u2744\ufe0f",
        "description": "Cooldown workout duration",
    },
}


def get_aggregate_sum_features():
    """Features that use SUM aggregation."""
    return {k for k, v in FEATURE_SPEC.items() if v["aggregation"] == AGG_SUM}


def get_display_value(feature: str, value: float) -> float:
    """Apply display_scale if defined (e.g. 0.98 -> 98 for blood_oxygen)."""
    spec = FEATURE_SPEC.get(feature, {})
    scale = spec.get("display_scale", 1)
    return value * scale


def get_display_unit(feature: str) -> str:
    """Display unit for chart Y-axis."""
    return FEATURE_SPEC.get(feature, {}).get("display_unit", "")


def get_display_format(feature: str) -> str:
    """Format string for chart tooltip/value."""
    return FEATURE_SPEC.get(feature, {}).get("format", "{:.2f}")
